---
- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: Pull shubhang123/chat-application-server
      docker_image:
        name: shubhang123/chat-application-server
        source: pull
    - name: Pull shubhang123/chat-application-client
      docker_image:
        name: shubhang123/chat-application-client
        source: pull
